In [1]:
import yfinance as yf
amazon = yf.Ticker("AMZN")

# https://medium.com/codestorm/how-to-get-data-from-yahoo-finance-using-python-8d087fe42b10 
# https://pypi.org/project/yfinance/

In [2]:
amazon.info

{'address1': '410 Terry Avenue North',
 'city': 'Seattle',
 'state': 'WA',
 'zip': '98109-5210',
 'country': 'United States',
 'phone': '206 266 1000',
 'website': 'https://www.amazon.com',
 'industry': 'Internet Retail',
 'sector': 'Consumer Cyclical',
 'longBusinessSummary': "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions through online and physical stores in North America and internationally. It operates through three segments: North America, International, and Amazon Web Services (AWS). The company's products offered through its stores include merchandise and content purchased for resale; and products offered by third-party sellers. It also manufactures and sells electronic devices, including Kindle, Fire tablets, Fire TVs, Rings, Blink, eero, and Echo; and develops and produces media content. In addition, the company offers programs that enable sellers to sell their products in its stores; and programs that allow authors, musicians, filmmakers, Twitch streamers, skill and app developers, and others to publish and sell content. Further, it provides compute, storage, database, analytics, machine learning, and other services, as well as fulfillment, advertising, and digital content subscriptions. Additionally, the company offers Amazon Prime, a membership program. It serves consumers, sellers, developers, enterprises, content creators, and advertisers. The company was incorporated in 1994 and is headquartered in Seattle, Washington.",
 'fullTimeEmployees': 1541000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jeffrey P. Bezos',
   'age': 58,
   'title': 'Founder & Exec. Chairman',
   'yearBorn': 1964,
   'fiscalYear': 2022,
   'totalPay': 1681840,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Andrew R. Jassy',
   'age': 54,
   'title': 'Pres, CEO & Director',
   'yearBorn': 1968,
   'fiscalYear': 2022,
   'totalPay': 1298723,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Brian T. Olsavsky',
   'age': 58,
   'title': 'Sr. VP & CFO',
   'yearBorn': 1964,
   'fiscalYear': 2022,
   'totalPay': 319850,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. David A. Zapolsky',
   'age': 58,
   'title': 'Sr. VP, Gen. Counsel & Sec.',
   'yearBorn': 1964,
   'fiscalYear': 2022,
   'totalPay': 319850,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Douglas J. Herrington',
   'age': 55,
   'title': 'Chief Exec. Officer of Worldwide Amazon Stores',
   'yearBorn': 1967,
   'fiscalYear': 2022,
   'totalPay': 335438,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adam N. Selipsky',
   'age': 55,
   'title': 'Chief Exec. Officer of Amazon Web Services, Inc.',
   'yearBorn': 1967,
   'fiscalYear': 2022,
   'totalPay': 360613,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Shelley L. Reynolds',
   'age': 57,
   'title': 'VP, Worldwide Controller & Principal Accounting Officer',
   'yearBorn': 1965,
   'fiscalYear': 2009,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Werner  Vogels',
   'title': 'Chief Technology Officer',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Dave  Fildes',
   'title': 'Director of Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Anuradha  Aggarwal',
   'title': 'CMO & Director of User Growth',
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 4,
 'boardRisk': 8,
 'compensationRisk': 10,
 'shareHolderRightsRisk': 2,
 'overallRisk': 10,
 'governanceEpochDate': 1680307200,
 'compensationAsOfEpochDate': 1672444800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 109.82,
 'open': 107.73,
 'dayLow': 104.33,
 'dayHigh': 109.48,
 'regularMarketPreviousClose': 109.82,
 'regularMarketOpen': 107.73,
 'regularMarketDayLow': 104.33,
 'regularMarketDayHigh': 109.48,
 'payoutRatio': 0.0,
 'forwardPE': 42.18,
 'volume': 130715946,
 'regularMarketVolume': 130715946,
 'averageVolume': 64576782,
 'averageVolume10days': 77142790,
 'averageDailyVolume10Day': 77142790,
 'bid': 104.98,
 'ask': 105.0,
 'bidSize': 900,
 'askSize': 1800,
 'marketCap': 1081706086400,
 'fiftyTwoWeekLow': 81.43,
 'fiftyTwoWeekHigh': 146.57,
 'fiftyDayAverage': 98.942,
 'twoHundredDayAverage': 106.82795,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'enterpriseValue': 1080573558784,
 'profitMargins': 0.0,
 'sharesOutstanding': 10257999872,
 'sharesShort': 59071722,
 'sharesShortPriorMonth': 56470494,
 'sharesShortPreviousMonthDate': 1678838400,
 'dateShortInterest': 1681430400,
 'sharesPercentSharesOut': 0.0058,
 'heldPercentInsiders': 0.09733,
 'heldPercentInstitutions': 0.60428,
 'shortRatio': 1.05,
 'shortPercentOfFloat': 0.0076,
 'impliedSharesOutstanding': 0,
 'bookValue': 14.259,
 'priceToBook': 7.395329,
 'lastFiscalYearEnd': 1672444800,
 'nextFiscalYearEnd': 1703980800,
 'mostRecentQuarter': 1680220800,
 'trailingEps': -0.26,
 'forwardEps': 2.5,
 'pegRatio': -0.28,
 'lastSplitFactor': '20:1',
 'lastSplitDate': 1654473600,
 '52WeekChange': -0.15301204,
 'SandP52WeekChange': 0.0033931732,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'AMZN',
 'underlyingSymbol': 'AMZN',
 'shortName': 'Amazon.com, Inc.',
 'longName': 'Amazon.com, Inc.',
 'firstTradeDateEpochUtc': 863703000,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '261fd26b-0151-3813-b0d0-97e4ed4c6505',
 'messageBoardId': 'finmb_18749',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 105.45,
 'targetHighPrice': 156.5,
 'targetLowPrice': 90.0,
 'targetMeanPrice': 132.49,
 'targetMedianPrice': 134.0,
 'recommendationMean': 1.8,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 44,
 'revenuePerShare': 50.445,
 'grossProfits': 225152000000,
 'grossMargins': 0.0,
 'ebitdaMargins': 0.0,
 'operatingMargins': 0.0,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.2353}

In [16]:
hist = amazon.history(period="5y")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2018-04-30 00:00:00-04:00,79.125000,79.800003,78.046997,78.306503,109282000,0.0,0.0
2018-05-01 00:00:00-04:00,78.161003,79.250000,77.609001,79.112999,91442000,0.0,0.0
2018-05-02 00:00:00-04:00,79.049004,79.425003,78.318001,78.484001,87206000,0.0,0.0
2018-05-03 00:00:00-04:00,78.000504,78.739998,77.301003,78.603996,85038000,0.0,0.0
2018-05-04 00:00:00-04:00,78.122498,79.245003,78.109497,79.047501,68872000,0.0,0.0
...,...,...,...,...,...,...,...
2023-04-24 00:00:00-04:00,107.660004,109.230003,105.070000,106.209999,69575600,0.0,0.0
2023-04-25 00:00:00-04:00,104.910004,105.449997,102.449997,102.570000,65026800,0.0,0.0
2023-04-26 00:00:00-04:00,105.040001,106.620003,104.099998,104.980003,73803800,0.0,0.0
2023-04-27 00:00:00-04:00,108.160004,110.860001,106.800003,109.820000,149961200,0.0,0.0
2023-04-28 00:00:00-04:00,107.730003,109.480003,104.330002,105.449997,130565000,0.0,0.0

In [17]:
amazon.actions

                           Dividends  Stock Splits
Date
2022-06-06 00:00:00-04:00        0.0          20.0

In [28]:
# https://pypi.org/project/yahoofinancials/

from yahoofinancials import YahooFinancials
tickers = ['AMZN']
yahoo_financials = YahooFinancials(tickers, concurrent=True, max_workers=8, country="US")
balance_sheet_data_qt = yahoo_financials.get_financial_stmts('quarterly', 'balance')
print(balance_sheet_data_qt)

#proxy_addresses = [ "mysuperproxy.com:5000", "mysuperproxy.com:5001"]
#yahoo_financials = YahooFinancials(tickers, concurrent=True, proxies=proxy_addresses)
#balance_sheet_data_qt = yahoo_financials.get_financial_stmts('quarterly', 'balance')
#print(balance_sheet_data_qt)

{'balanceSheetHistoryQuarterly': {'IWDA': []}}